### ISSUE TITLE
Git LFS data quota exceeded

### ISSUE THREAD

**Issue by entn-at** [OscarVanL/LibriTTS-British-Accents#1]
Hi,

Thank you for your effort in creating this dataset! This is just to let you know that the data currently cannot be accessed, as apparently the git LFS data quota has been exceeded:
```
$ git lfs fetch
fetch: Fetching reference refs/heads/master
batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.
error: failed to fetch some objects from 'https://github.com/OscarVanL/LibriTTS-British-Accents.git/info/lfs'
```
Note that I'm not at all asking you to pay for data packs! I'm merely reporting this here. Perhaps another option would be to upload the data to a Google Drive shared folder and posting the link in the README.

Cheers,
Ewald

**Comment by entn-at** [comment]
On second thought, I may have misunderstood how Git LFS data quotas apply (https://docs.github.com/en/free-pro-team@latest/github/managing-large-files/about-storage-and-bandwidth-usage#bandwidth-quota). Please disregard this, the issue may be on my side.

**Comment by OscarVanL** [comment]
Thanks for this, when I made the repo I wasn't aware Git LFS had limits. (I also don't want you to have to buy a data pack)

I was intending to search for an alternative. Do you know if Google Drive has bandwidth limits?

**Comment by entn-at** [comment]
I do believe it has quotas, but I saw Google Drive being used for hosting a lot of ML models (see for example espnet, TensorflowTTS, or even nVidia's Tacotron2/WaveGlow models). The same is likely true for Dropbox, Mega, etc.

Not to worry, though, as I can simply extract the dataset from the original LibriTTS files using the provided `SPEAKERS_<ACCENT>.txt` files.

Thanks!

**Comment by OscarVanL** [comment]
Yeah, the process for making this dataset yourself isn't so bad, just it
requires downloading ~80GB of zipped files, which then extract to about
300GB, so it's a little irritating and time consuming, but that is a
workaround until I look for alternative hosting.

**Comment by OscarVanL** [comment]
Here are some mirrors:

[Mega](https://mega.nz/file/JXAnAajA#VVrtPxoDBYIjipoUe_hDYTrvaiKuV2pELZVQWVeOMoc)

[Google Drive](https://drive.google.com/file/d/1o50YMBASmd4NODd-7a5bCiiqAMEUgn0v/view?usp=sharing)
